// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPlj-gI15VXloaUhatSwCaHqwJmqi3jvw',
    appId: '1:43818616697:web:57c99a7e150c2530e911a8',
    messagingSenderId: '43818616697',
    projectId: 'instaclone-ed42d',
    authDomain: 'instaclone-ed42d.firebaseapp.com',
    storageBucket: 'instaclone-ed42d.appspot.com',
    measurementId: 'G-5V60W57W9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHUOnzF7Yy-RIGGkYDJdsC-RKtubiYyQ8',
    appId: '1:43818616697:android:1a98f281cc4f94e9e911a8',
    messagingSenderId: '43818616697',
    projectId: 'instaclone-ed42d',
    storageBucket: 'instaclone-ed42d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1c6GNob5-19JKx-ujnbyY90Dyjn-mjZY',
    appId: '1:43818616697:ios:1b07da20cb7af062e911a8',
    messagingSenderId: '43818616697',
    projectId: 'instaclone-ed42d',
    storageBucket: 'instaclone-ed42d.appspot.com',
    androidClientId: '43818616697-nb18hoaevse0nps8i3ih5kcuutdkdcin.apps.googleusercontent.com',
    iosClientId: '43818616697-3hjiq44oua9v4cjl81cm60j0lpmd2meg.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1c6GNob5-19JKx-ujnbyY90Dyjn-mjZY',
    appId: '1:43818616697:ios:1b07da20cb7af062e911a8',
    messagingSenderId: '43818616697',
    projectId: 'instaclone-ed42d',
    storageBucket: 'instaclone-ed42d.appspot.com',
    androidClientId: '43818616697-nb18hoaevse0nps8i3ih5kcuutdkdcin.apps.googleusercontent.com',
    iosClientId: '43818616697-3hjiq44oua9v4cjl81cm60j0lpmd2meg.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );
}
